---
- hosts: fortigates
  gather_facts: no

  tasks:

  - name: "Configure <system console> settings"
    delegate_to: localhost
    fortiosconfig:
     action: "ssh"
     host:  "{{ ansible_host }}"
     username: "{{ ansible_user }}"
     password: "{{ ansible_password }}"
     commands: |
                config system console
                  set output standard
                end
    register: output

  - fail:
      msg: "There was an error during execution..."
    when: output.meta.err == true

  - debug:
      msg: "It's all OK!"