---
- hosts: fortigates
  gather_facts: no

  vars:

  tasks:

  - name: "Configure <central-management> settings..."
    delegate_to: localhost
    fortiosconfig:
      action: "set"
      ssl_verify: False
      host:  "{{ ansible_host }}"
      username: "{{  ansible_user }}"
      password: "{{ ansible_password }}"
      config: "system central-management"
      config_parameters:
        type: fortimanager
        fmg: "{{ fortimanager_ip }}"
        mode: normal
        include-default-servers: enable
        server-list:
        - addr-type: ipv4
          server-address: "{{ fortimanager_ip }}"
          server-type: "update rating" 

  - name: "Configure <log fortianalyzer> settings..."
    delegate_to: localhost
    fortiosconfig:
      action: "set"
      ssl_verify: False
      host:  "{{ ansible_host }}"
      username: "{{  ansible_user }}"
      password: "{{ ansible_password }}"
      config: "log.fortianalyzer setting"
      config_parameters:
        status: enable
        server: "{{ fortimanager_ip }}"
        upload-option: realtime

  - debug:
      msg: "It's all OK!"