---
- name: Compare states (via YAML files)
  hosts: localhost
  gather_facts: no
  connection: local

  tasks:

  - fail:
      msg: |
        It's deprecated directory input format.
        Use -e 'dir1=<directory>/<revision> dir2=<directory>/<revision>'"
    when: dir1.startswith("out/run") or dir2.startswith("out/run")
        
  - name: Find diff
    copy:
      dest: "out/parsed_data/{{ dir1 }}/one-line/{{ item.split('/')[-1] }}"
      src: "out/parsed_data/{{ dir2 }}/one-line/{{ item.split('/')[-1] }}"
    diff: yes
    check_mode: yes
    with_items: "{{ lookup('fileglob', 'out/parsed_data/{{ dir1 }}/one-line/*').split(',') }}"