---
- hosts: all
  gather_facts: no

  vars:
    ipv4_dict: []
    ipv6_dict: []
    policyid: 25032021
    policy_type: 

  tasks:

  - name: Collect only facts returned by facter
    delegate_to: localhost
    setup:


  #
  #
  # IPv4 configuration

  - name: "Configure <firewall address> settings"
    delegate_to: localhost
    fortiosconfig:
      action: "set"
      ssl_verify: False
      host:  "{{ ansible_host }}"
      username: "{{  ansible_user }}"
      password: "{{ ansible_password }}"
      vdom: "{{ data_vdom }}"
      config: "firewall address"
      config_parameters:
        name: "test___{{ item }}"
        type: ipmask
        subnet: "{{ item }} 255.255.255.255"
        color: 5
    with_items: 
    - "{{ ansible_all_ipv4_addresses }}"

  - set_fact:
      ipv4_dict: "{{ ipv4_dict + [{ 'name': 'test___' + item }] }}"
    with_items: 
    - "{{ ansible_all_ipv4_addresses }}"

  - name: "Configure <firewall policy> settings"
    delegate_to: localhost
    fortiosconfig:
      action: "set"
      ssl_verify: False
      host:  "{{ ansible_host }}"
      username: "{{  ansible_user }}"
      password: "{{ ansible_password }}"
      vdom: "{{ data_vdom }}"
      config: "firewall policy"
      config_parameters:
        policyid: "{{ policyid }}"
        name: "test___{{ inventory_hostname }}"
        comments: "Policy for test clients. Created by Solidex organization."
        srcintf: "{{ inside }}"
        dstintf: "{{ outside }}"
        srcaddr: "{{ ipv4_dict }}"
        dstaddr:
        - name: "all"
        service:
        - name: "ALL"
        action: "accept"
        status: "enable"
        logtraffic: "all"
        schedule: "always"
        nat: "enable"

  - debug:
      msg: "IPv4 configuration is completed!"

  - meta: end_play
    when: ipv6 == false


  # 
  #
  #  IPv6 configuration

  - name: "Configure <firewall address6> settings"
    delegate_to: localhost
    fortiosconfig:
      action: "set"
      ssl_verify: False
      host:  "{{ ansible_host }}"
      username: "{{  ansible_user }}"
      password: "{{ ansible_password }}"
      vdom: "{{ data_vdom }}"
      config: "firewall address6"
      config_parameters:
        name: "test___{{ item }}"
        type: ipprefix
        ip6: "{{ item }}/128"
        color: 6
    with_items: 
    - "{{ ansible_all_ipv6_addresses }}"

  - set_fact:
      ipv6_dict: "{{ ipv6_dict + [{ 'name': 'test___' + item }] }}"
    with_items: 
    - "{{ ansible_all_ipv6_addresses }}"

  - name: "Configure <firewall policy6> settings"
    delegate_to: localhost
    fortiosconfig:
      action: "set"
      ssl_verify: False
      host:  "{{ ansible_host }}"
      username: "{{  ansible_user }}"
      password: "{{ ansible_password }}"
      vdom: "{{ data_vdom }}"
      config: "firewall policy6"
      config_parameters:
        policyid: "{{ policyid }}"
        name: "test6___{{ inventory_hostname }}"
        comments: "Policy for test clients. Created by Solidex organization."
        srcintf: "{{ inside }}"
        dstintf: "{{ outside }}"
        srcaddr: "{{ ipv6_dict }}"
        dstaddr:
        - name: "all"
        service:
        - name: "ALL"
        action: "accept"
        status: "enable"
        logtraffic: "all"
        schedule: "always"
        nat: "enable"

  - debug:
      msg: "IPv6 configuration is completed!"
