---
- hosts: fortigates
  gather_facts: no

  tasks:

  - name: "Show full configuration"
    delegate_to: localhost
    fortiosconfig:
     action: "ssh"
     host:  "{{ ansible_host }}"
     username: "{{ ansible_user }}"
     password: "{{ ansible_password }}"
     commands: |
              show full
    register: output

  - fail:
      msg: "There was an error during execution:\n{{ output.meta.out[-500:].split('\n')[1:] | join('\n') }}"
    when: output.meta.err == true

  - fail:
      msg: "Seems like output is not full:\n...\n{{ output.meta.out[-500:].split('\n')[1:] | join('\n') }}"
    when: (output.meta.out | trim)[-1] != "#"

  - debug:
      msg: "It's all OK!"