---
- hosts: all
  gather_facts: no

  tasks:

  - name: "Show full configuration"
    delegate_to: localhost
    fortiosconfig:
     action: "ssh"
     host:  "{{ ansible_host }}"
     username: "{{ ansible_user }}"
     password: "{{ ansible_password }}"
     commands: |
              show full
    register: output

  - fail:
      msg: "There was an error during execution..."
    when: output.meta.err == true

  - debug:
      msg: "{{ output }}"